### ISSUE TITLE
能麻烦你更新一下Apex-NoRecoil项目吗？赴汤蹈火啊曾哥！

### ISSUE THREAD

**Issue by xslzlccc** [richardzzp/techtrainingcamp-security-12#3]
能麻烦你更新一下Apex-NoRecoil项目吗？赴汤蹈火啊曾哥！

**Comment by richardzzp** [comment]
？？？？？？？？？？

**Comment by xslzlccc** [comment]
> 

![image](https://github.com/richardzzp/techtrainingcamp-security-12/assets/50007642/bc75f32b-bc6f-4421-8a1a-0107446f744c)
 我看作者的更新日志里提到你维护过这个项目。

**Comment by richardzzp** [comment]
你看一下这个库，他更新了L-star和Re-45的识别代码。只是mgsweet暂时没通过分支合并，应该是可以用的。
https://github.com/MoralFst/Apex-NoRecoil-2021/tree/patch-2

**Comment by richardzzp** [comment]
这个是合并分支的请求：https://github.com/mgsweet/Apex-NoRecoil-2021/pull/287

**Comment by xslzlccc** [comment]
> 你看一下这个库，他更新了L-star和Re-45的识别代码。只是mgsweet暂时没通过分支合并，应该是可以用的。 https://github.com/MoralFst/Apex-NoRecoil-2021/tree/patch-2

get it！
